JDK-8180450 article
RedHatPerf/redhatperf.github.io pull request #4
Opened 2022-11-21 16:48 UTC by franz1981

2022-11-22 12:03 UTC, johnaohara requested changes
Franz, I have made some suggestions. We also need to co-ordinate creating an author profile for you

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +This article is a detailed and complementary content to https://youtu.be/G40VfIsnCdo[Quarkus Insights #107].
We can inline the video here, see: https://github.com/RedHatPerf/redhatperf.github.io/blame/dev/content/post/coordinated-omission/index.adoc#L299

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +This article is a detailed and complementary content to https://youtu.be/G40VfIsnCdo[Quarkus Insights #107].
And how it is rendered: https://redhatperf.github.io/post/coordinated-omission/#_see_it_in_action

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +The mentioned Quarkus Insights episode treats a breed of the scary (was registered at Halloween on purpose) JDK issue https://bugs.openjdk.org/browse/JDK-8180450["JDK-8180450: secondary_super_cache d
```suggestion
This episode treats a breed of issues caused by the scary (was registered at Halloween on purpose) JDK issue; https://bugs.openjdk.org/browse/JDK-8180450["JDK-8180450: secondary_super_cache does not scale well"]
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +that has caused massive performance degradation on several middleware frameworks eg Netty, Vert-x, Mutiny, Hibernate, Quarkus...
```suggestion
that can causes massive performance degradation on several middleware frameworks e.g. Netty, Vert-x, Mutiny, Hibernate, Quarkus...
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +For who hasn't yet watched https://youtu.be/G40VfIsnCdo[Quarkus Insights #107], `JDK-8180450` is a severe scalability penalty happening while
```suggestion
For those who haven't yet watched https://youtu.be/G40VfIsnCdo[Quarkus Insights #107], `JDK-8180450` is a severe scalability penalty happening while
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +among multiple threads, further causing https://en.wikipedia.org/wiki/False_sharing[False Sharing] with its surrounding fields eg `Klass::_secondary_supers`.
```suggestion
from multiple threads, which in turn causes https://en.wikipedia.org/wiki/False_sharing[False Sharing] with its surrounding fields eg `Klass::_secondary_supers`.
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +This https://github.com/openjdk/jdk11/blob/master/src/hotspot/share/oops/klass.hpp#L133[JDK 11 snippet] shows both fields and
Do we want to point to master branch here? or should we link to a stable branch? this link will break if master branch is updated in the future

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +To make it more concrete: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Integer.html[`Integer`] 's implement both `Comparable` and `Serializable`;
```suggestion
To make it more concrete: 

* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Integer.html[`Integer`] 's implement both `Comparable` and `Serializable`
```

We also need to think about how links encapsulated in `` are displayed, to make it clear they are links

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +`_secondary_supers` contains both `Comparable` and `Serializable`, while `_secondary_super_cache` is used like this:
```suggestion
* `_secondary_supers` contains both `Comparable` and `Serializable`, 
* `_secondary_super_cache` is used byt he JVM like this:
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +The `checkcast` on `useComparable` doesn't need to search `Comparable` on the `_secondary_supers` array, but can
```suggestion
The JVM does not need to search for `Comparable` in the `_secondary_supers` array when evaluating `checkcast` in the `useComparable`, instead it can
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +use `_secondary_super_cache`, saving useless work.
```suggestion
use the `_secondary_super_cache` field, saving useless work.
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +So, *How to cause such massive updates to the cache field*?
```suggestion
So, *What causes massive amounts of updates to the cache field*?
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +The answer is simpler then it seems: making it ping-pong between one or more values contained in `_secondary_supers`!
```suggestion
The answer is simpler then it seems: making it ping-pong between multiple values contained in `_secondary_supers`!
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +The comments on the code shows what happen if such code is called by a single thread, causing twice `_secondary_super_cache`
```suggestion
The comments in the code show what happens if this method is called by a single thread, causing two `_secondary_super_cache`
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +invalidations for each `compareAndSerializable` method execution, but
```suggestion
invalidations for every `compareAndSerializable` method execution, but
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +*What happen if there are more caller threads*?
```suggestion
*What happens if there are more than one thread*?
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +https://www.techempower.com/[Techempower Benchmark] to validate https://quarkus.io[Quarkus]'s performance regressions and
```suggestion
https://www.techempower.com/[Techempower Benchmark] to validate https://quarkus.io[Quarkus]'s performance regressions.
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +hitting such scalability bottleneck in our lab has caused a performance degradation quite significant while running on our `Intel(R) Xeon(R) Gold 5218 CPU` with 64 logical cores (32 without Hyper-Thr
```suggestion
Hitting such scalability bottleneck in our lab has caused a performance degradation quite significant while running on our `Intel(R) Xeon(R) Gold 5218 CPU` with 64 logical cores (32 without Hyper-Threading, splitted in 2 https://en.wikipedia.org/wiki/Non-uniform_memory_access[NUMA] nodes):
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +The scariest part has yet to come: what we've discovered while investigating on the https://github.com/netty/netty/issues/12708[most severe case]
```suggestion
The scariest part has yet to come: what we discovered while investigating the https://github.com/netty/netty/issues/12708[most severe case]
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +Furthermore, few weeks after the Quarkus Insights recording, Netflix has published an https://netflixtechblog.com/seeing-through-hardware-counters-a-journey-to-threefold-performance-increase-2721924a
```suggestion
Furthermore, a few weeks after the Quarkus Insights recording, Netflix has published an https://netflixtechblog.com/seeing-through-hardware-counters-a-journey-to-threefold-performance-increase-2721924a2822[article]
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +the latter provided some hint that something wrong was going on.
```suggestion
the latter provided some hint that something incorrect was occurring.
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +The above https://netflixtechblog.com/java-in-flames-e763b3d32166[flamegraph] shows at the bottom left of the graph
```suggestion
In the above https://netflixtechblog.com/java-in-flames-e763b3d32166[flamegraph], the bottom left of the graph shows
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +some costy method, but failing to report the right ones: not useful to fix it!
```suggestion
some costy methods, but failing to report the correct methods: not useful to fix it!
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +which modifies the x86 register used to track the https://en.wikipedia.org/wiki/Stack_register[Stack Pointer]
```suggestion
which modifies the x86 register that is used to track the https://en.wikipedia.org/wiki/Stack_register[Stack Pointer]
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +and key to detect the sampled trace caller method (more on this https://github.com/jvm-profiling-tools/async-profiler/issues/673#issuecomment-1304504745[Async Profiler issue's comment]).
```suggestion
and key to determine the sampled calling method (more on this https://github.com/jvm-profiling-tools/async-profiler/issues/673#issuecomment-1304504745[Async Profiler issue's comment]).
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +Thanks to this investigation a recent https://bugs.openjdk.org/browse/JDK-8287425[JDK change] fixing the mentioned behaviour
```suggestion
Thanks to this investigation, a recent https://bugs.openjdk.org/browse/JDK-8287425[JDK change] fixing the mentioned behaviour
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +has been https://github.com/openjdk/jdk11u-dev/pull/1524[back-ported to JDK 11] as well,
```suggestion
(which has been https://github.com/openjdk/jdk11u-dev/pull/1524[back-ported to JDK 11]) ,
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +making this issue easier to be spotted by existing traditional (`AsyncGetCallTrace`-based) Java Profilers: a proper "Community Happy End".
```suggestion
making this issue more easily spotted with existing (`AsyncGetCallTrace`-based) Java Profilers: a proper "Community Happy End".
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +In addition to the above issue, https://en.wikipedia.org/wiki/False_sharing[False Sharing] is responsible to make profiling tools
```suggestion
In addition to the above issue, https://en.wikipedia.org/wiki/False_sharing[False Sharing] is further confuses profiling tools.
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +even more confused.
```suggestion
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +On any invalidation of `Klass::_secondary_super_cache`, a search over `Klass::_secondary_supers` is performed,
```suggestion
For every invalidation of `Klass::_secondary_super_cache`, a search over `Klass::_secondary_supers` is performed,
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +getting a severe penalty (if sitting in the same cache-line of the "noisy" field) and impacting other innocent code paths too:
```suggestion
causing a severe penalty (if stored in the same cache-line of the "noisy" field) and impacting other innocent code paths too:
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +The snippet above shows that performing a type check over a not implemented interface always
```suggestion
The snippet above shows that performing a type check for a non-implemented interface always
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +perform a slow path search over `_secondary_supers`, forcing loading the related field and causing
```suggestion
causes the JVM to perform a slow path search over `_secondary_supers`. This in turn forces loading the related field and causes
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +some ping-pong of cache coherency traffic to happen, slowing down the innocent load instruction and making a profiler
```suggestion
a ping-pong of cache coherency traffic. This has the effect of slowing down the innocent load instruction and causes a profiler
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +to highlight it.
```suggestion
to highlight it as a cpu bottlneck.
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +The issue is better detailed in this https://youtu.be/G40VfIsnCdo?t=1411[Quarkus Insights part]
```suggestion
The issue is detailed in this https://youtu.be/G40VfIsnCdo?t=1411[Quarkus Insights part]
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +Thanks both, the JDK Optimizing Compiler can drop type check operations not making the issue to happen.
```suggestion
Thanks to both optimizations, the JDK Compiler can drop type-check operations preventing the issue from happening.
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +This smart compiler behaviour, together with the previous mentioned reasons, has made this issue to lie dormant and unnoticed for some time,
```suggestion
This smart compiler behaviour, together with the previous mentioned profiler issues, has meant this issue has lay dormant and unnoticed for some time,
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +especially on benchmarking rigs, where the simplicity of the use case was leaving the compiler more
```suggestion
especially in benchmarking environments, where overly simplistic use cases were leaving the compiler more
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +we've developed a https://github.com/raphw/byte-buddy[ByteBuddy]-powered https://github.com/RedHatPerf/type-pollution-agent[Java Agent] that has helped fixing the
```suggestion
we've developed a https://github.com/raphw/byte-buddy[ByteBuddy]-powered https://github.com/RedHatPerf/type-pollution-agent[Java Agent]. This has helped fix the
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +the https://bugs.openjdk.org/browse/JDK-8180450[scalability JDK issue] has raised priority and targeting the Java 21 release.
```suggestion
the https://bugs.openjdk.org/browse/JDK-8180450[scalability JDK issue] now has raised a priority and a fix will be targeted for the Java 21 release.
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +As said in the mentioned Quarkus Insights, some fixes have helped to use different and mode idiomatic code
```suggestion
As mentioned in Quarkus Insights, some fixes have helped to use different and more idiomatic code
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +solutions to replace a misuse (often abuse) of the existing type check-based logic, often leading to better performance and,
```suggestion
solutions to replace the misuse (often abuse) of the existing type check-based logic, often leading to better performance and,
```

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +date: 2022-11-16T00:00:00Z
need top update this date to the publish date

2022-11-22 12:03 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +categories: ['performance', 'benchmarking', 'methodology']
need to review these categories, possibly ['profiling', 'tooling', 'JVM performance', 'JVM internls'] ? wdyt i haven't really thought about the categories we should use

2022-11-22 13:34 UTC, franz1981 commented on content/post/type-check-scalability-issue/index.adoc
> +This https://github.com/openjdk/jdk11/blob/master/src/hotspot/share/oops/klass.hpp#L133[JDK 11 snippet] shows both fields and
In theory is an archived one, so shouldn't happen, but better be safe then sorry, good point!

2022-11-22 15:23 UTC, franz1981 commented on content/post/type-check-scalability-issue/index.adoc
> +This article is a detailed and complementary content to https://youtu.be/G40VfIsnCdo[Quarkus Insights #107].
Nice one, I've referenced few times already the same video but at different minutes, let me check if it makes sense to embed it once at the beginning (leaving the others as ref links, without thumbnail) or do it for the most important ones

2022-11-22 16:26 UTC, johnaohara requested changes
@franz1981 I have added code formatting to the blog, the suggested changes will apply the code highlighting in the rendered website

2022-11-22 16:26 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +++++
```suggestion
++++
<div class="imageblock right text-center">
<div class="content" style="text-align: center;">
<iframe width="560" height="315" src="https://www.youtube.com/embed/G40VfIsnCdo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
</div>
++++
```

The video is not rendering correctly on my local site, this should fix it

2022-11-22 16:26 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +```
```suggestion
{{< highlight cpp >}}
class Klass : public Metadata {
  // ...
  // Cache of last observed secondary supertype
  Klass*      _secondary_super_cache;
  // Array of all secondary supertypes
  Array<Klass*>* _secondary_supers;
  // ...
{{< / highlight >}}
```

2022-11-22 16:26 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +```
```suggestion
{{< highlight java >}}
    Object o = new Integer(1);
    // _seconday_super_cache is empty
    // search Comparable on [ Comparable, Serializable ]
    if (o instanceof Comparable) {
        // _seconday_super_cache := Comparable -> cache HIT!
        useComparable((Comparable) o);
    }
{{< / highlight >}}
```

2022-11-22 16:26 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +```
```suggestion
{{< highlight java>}}
    // o.getClass() == Integer.class
    public static void compareAndSerialize(Object o) {
        if (o instanceof Comparable) {
            // _seconday_super_cache := Comparable
            useComparable((Comparable) o);
        }
        if (o instanceof Serializable) {
            // _seconday_super_cache := Serializable
            useSerializable((Serializable) o);
        }
    }
{{< / highlight >}}
```

2022-11-22 16:26 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +```
```suggestion
{{< highlight java>}}
    // o.getClass() == Integer.class
    // _secondary_super_cache always != CharSequence
    // slow path search on _secondary_supers := [ Comparable, Serializable ]
    if (o instanceof CharSequence) {
        // never happen
    } else {
        // always happen
    }
{{< / highlight >}}
```

2022-11-23 10:45 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +This https://github.com/openjdk/jdk11/blob/master/src/hotspot/share/oops/klass.hpp#L133[JDK 11 snippet] shows both fields and
@franz1981 do you want to update this link before the post is merged?

2022-11-23 10:46 UTC, johnaohara commented
@franz1981 do you have any more changes to push?

2022-11-23 10:55 UTC, franz1981 commented
Yep, I would like to address the last comments and add a sentence about the Jdk fix + clarifying the stack register part related profilers fall

2022-11-23 16:02 UTC, johnaohara requested changes
Some grammar changes

2022-11-23 16:02 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +which modifies the stack size and by consequence the x86 register used to track the https://en.wikipedia.org/wiki/Stack_register[Stack Pointer]
```suggestion
which modifies the stack size and as a consequence the x86 register used to track the https://en.wikipedia.org/wiki/Stack_register[Stack Pointer]
```

2022-11-23 16:02 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +As a separate effort we've evaluated with the OpenJDK Red Hat team alternatives fixes to the infamous JDK issue as well, ending up rejecting ad-hoc flags to disable such optimization (as it was desig
```suggestion
As a separate effort, we've worked with the OpenJDK Red Hat team to evaluate alternative fixes to the infamous JDK issue; we have rejected ad-hoc flags to disable such optimization (as it was designed to operate)
```

2022-11-23 16:02 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +because too harmful for existing users, which unconsciously have benefited from it till now. We are trusty that our feedbacks
```suggestion
; due to the potentially harmful effects on existing users, which unconsciously have benefited from it till now. We trust that the feedback we have received
```

2022-11-23 16:02 UTC, johnaohara commented on content/post/type-check-scalability-issue/index.adoc
> +will help making a better decision for the Java Community, present and future.
```suggestion
will help provide a better outcome for the Java Community, present and future.
```

2022-11-24 13:05 UTC, franz1981 commented
@johnaohara I think we need a nice image to represent the article and a better title and we're ready to go :)

2022-11-24 13:07 UTC, franz1981 commented
Waiting @barreiro to look at it, maybe some sentence need some english rewording yet

2022-11-25 08:31 UTC, johnaohara approved these changes, later dismissed

2022-11-25 09:23 UTC, johnaohara approved these changes
LGTM

2022-11-25 09:24 UTC, merged